# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faketrello', '0002_auto_20160515_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='faketrello',
            name='status',
            field=models.CharField(default=-1, max_length=45),
            preserve_default=False,
        ),
    ]
