# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faketrello', '0003_faketrello_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faketrello',
            new_name='Task',
        ),
    ]
